# GitHub Pages Configuration Variables

# The theme of your site
remote_theme: nikahmadz/prime@v0.1

# The title of your site
title: Nik Ahmad Z

# A short description of your site's purpose
description: Senior Application Developer, Malaysia
