# GitHub Pages Configuration Variables

# The theme of your site
remote_theme: nikahmadz/pages@v0.1.10

# The title of your site
title: Nik Ahmad Z

# A short description of your site's purpose
description: Senior Application Developer, Malaysia
