# GitHub Pages Configuration Variables

remote_theme: nikahmadz/pages # The theme of your site

title: Nik Ahmad Z # The title of your site
description: Senior Application Developer in Malaysia
favicon: favicon.ico
# manifest: manifest.json
# color_scheme: 'light dark'
# theme_color: '#202020'
