# GitHub Pages Configuration Variables
remote_theme: nikahmadz/prime@v0.1.0-beta

# The title of your site
title: Nik Ahmad Z (v.0.1.0-beta)

# A short description of your site's purpose
# description:
